# -*- coding: utf-8 -*-
"""
deck_raw.py — 考研必考词原始词表（数据源）
============================================
词表来源：《红宝书·考研英语词汇（精缩版）》必考词部分，
从 Unit 1 / Unit 2 / Unit 3 扫描页 OCR 整理，覆盖常见考研高频词根词缀词族
（re- / con- / priv- / sub- / stand / com- / dis- / trans- / prim- 等）。
每条记录：(front 单词, phonetic 音标, back 中文释义)
"""
DECK_RAW = [
    # ---- Unit 1：re- / con- / priv- / sub- 词族 ----
    ("remote", "[rɪˈməʊt]", "adj.（时间、距离）遥远的；偏僻的；（关系）疏远的，冷淡的；极不相同的"),
    ("remove", "[rɪˈmuːv]", "v. 搬迁，移动；移开，挪走；去掉，消除；开除，撤职"),
    ("removal", "[rɪˈmuːvl]", "n. 移动，迁居，除去，切除；免职，开除"),
    ("remain", "[rɪˈmeɪn]", "v. 剩下，余留；留待，尚需；仍然是，依旧是"),
    ("remainder", "[rɪˈmeɪndə(r)]", "n. 剩余物，剩余时间，残余部分；余数，余项"),
    ("remains", "[rɪˈmeɪnz]", "n.（pl.）残余（物）；遗迹，废墟；遗体"),
    ("remedy", "[ˈremədi]", "n. 治疗（法），药品；补救（办法）；vt. 医治；补救，纠正"),
    ("remember", "[rɪˈmembə(r)]", "v. 记得，回想起，不忘记；代……问候"),
    ("remind", "[rɪˈmaɪnd]", "vt. 提醒，使想起"),
    ("render", "[ˈrendə(r)]", "v. 使得，使成为；给予，回报；提出，呈报"),
    ("contemporary", "[kənˈtemprəri]", "adj. 同时代的，同时发生的；现代的，当代的；n. 同代人"),
    ("contempt", "[kənˈtempt]", "n. 轻视，轻蔑；藐视，毫不畏惧"),
    ("content", "[ˈkɒntent]", "n. 容量，含量；（pl.）内容，目录；主题，要旨；adj. 满意的"),
    ("contend", "[kənˈtend]", "v. 竞争，争夺；声称，主张"),
    ("contest", "[ˈkɒntest]", "n. 竞赛，比赛；v. 争夺，竞争，争论，提出异议"),
    ("context", "[ˈkɒntekst]", "n. 上下文，语境；（事件发生的）环境，背景"),
    ("contract", "[ˈkɒntrækt]", "n. 合同，契约；v. 缩小，缩短；感染（疾病）"),
    ("contradict", "[ˌkɒntrəˈdɪkt]", "v. 反驳；同……相矛盾"),
    ("contrary", "[ˈkɒntrəri]", "adj. 相反的，对抗的；n. 相反事物，对立面"),
    ("contrast", "[ˈkɒntrɑːst]", "v. 使成对比，形成对比；n. 对照，对比；差异，差别"),
    ("diverse", "[daɪˈvɜːs]", "adj. 多种多样的，不同的"),
    ("diversion", "[daɪˈvɜːʃn]", "n. 转向，转移；转移注意力的事物；娱乐，消遣"),
    ("divert", "[daɪˈvɜːt]", "vt. 转移（某人的）注意力；（使）转向；挪用资金"),
    ("divide", "[dɪˈvaɪd]", "v. 分，划分；分裂；分配，分享；分隔；除；n. 差异，分歧"),
    ("dividend", "[ˈdɪvɪdend]", "n. 股息，红利，报酬；被除数"),
    ("division", "[dɪˈvɪʒn]", "n. 分开，分配；部门；差异，分歧；除法"),
    ("document", "[ˈdɒkjumənt]", "n. 公文，文件，文献，文档；v. 记录，记载（详情）"),
    ("documentary", "[ˌdɒkjuˈmentri]", "adj. 文献的，文件的；记录的，纪实的；n.（文献）纪录片"),
    ("execute", "[ˈeksɪkjuːt]", "vt. 实行，实施，履行；处决；执行（法令），使生效"),
    ("executive", "[ɪɡˈzekjətɪv]", "adj. 实行的，执行的，行政的；n. 经理，董事，高管；行政部门"),
    ("exemplify", "[ɪɡˈzemplɪfaɪ]", "vt. 例示，举例证明"),
    ("exert", "[ɪɡˈzɜːt]", "vt. 用（力），尽（力）；运用，行使，发挥；施加（压力）"),
    ("exhaust", "[ɪɡˈzɔːst]", "v. 使筋疲力尽；用完，耗尽；n. 排气装置；废气"),
    ("exist", "[ɪɡˈzɪst]", "vi. 存在，实际上有；生存，生活"),
    ("existence", "[ɪɡˈzɪstəns]", "n. 存在，生存；生活方式"),
    ("exotic", "[ɪɡˈzɒtɪk]", "adj. 由外国引进的；吸引人的；珍奇的，奇异的；n. 外来物"),
    ("moral", "[ˈmɒrəl]", "adj. 道德（上）的，道义的；品行端正的；n. 寓意；品行，道德规范"),
    ("morality", "[məˈræləti]", "n. 道德（规范），伦理；美德"),
    ("moreover", "[mɔːrˈəʊvə(r)]", "adv. 再者，此外，而且"),
    ("mostly", "[ˈməʊstli]", "adv. 几乎全部地，主要地，大部分"),
    ("prior", "[ˈpraɪə(r)]", "adj. 先前的，较早的；优先的；更重要的"),
    ("priority", "[praɪˈɒrəti]", "n.（时间、顺序等的）先，前，优先权；优先事项，最重要的事"),
    ("privacy", "[ˈprɪvəsi]", "n. 隐居；私事，隐私"),
    ("private", "[ˈpraɪvət]", "adj. 私人的，个人的；秘密的；私立的，私营的"),
    ("privilege", "[ˈprɪvəlɪdʒ]", "n. 特权，优惠；特殊的待遇，特殊的荣幸"),
    ("prudent", "[ˈpruːdnt]", "adj. 谨慎的，小心的；有先见之明的；会打算的"),
    ("submit", "[səbˈmɪt]", "v. 屈服，服从，投降；提交，呈递"),
    ("subordinate", "[səˈbɔːdɪnət]", "adj. 下级的；附属的，次要的；n. 下级"),
    ("subscribe", "[səbˈskraɪb]", "v. 捐助，赞助；订阅，订购；同意；签名"),
    ("subsequent", "[ˈsʌbsɪkwənt]", "adj. 随后的，后来的"),
    ("substance", "[ˈsʌbstəns]", "n. 物质；要旨，基本内容；实质，本质；财力，资产"),
    ("substantial", "[səbˈstænʃl]", "adj. 实质的，真实的；坚固的，结实的；大量的；重要的"),
    ("substitute", "[ˈsʌbstɪtjuːt]", "n. 代替者，代替物；v. 代替，替换"),
    ("subtle", "[ˈsʌtl]", "adj. 微妙的，巧妙的；细微的，细致的；精妙的，灵巧的"),
    ("associate", "[əˈsəʊʃieɪt]", "v.（使）联系，（使）联合；结交，交往；n. 伙伴，合伙人；adj. 副的"),
    ("association", "[əˌsəʊʃiˈeɪʃn]", "n. 协会，团体；联合，联系，交往；联想"),
    ("amend", "[əˈmend]", "vt. 修改，修订；改进，改善"),
    ("among", "[əˈmʌŋ]", "prep. 在……之中，在……中间"),
    ("amount", "[əˈmaʊnt]", "n. 数量，总额；vi.（to）达到……之多"),
    ("ample", "[ˈæmpl]", "adj. 充足的，丰富的；宽敞的，面积大的"),
    ("amuse", "[əˈmjuːz]", "vt. 逗乐，逗笑，给……提供娱乐（或消遣）"),
    # ---- Unit 2：stand / state / stay / star 词族 ----
    ("stand", "[stænd]", "v. 站，站立；坚持；忍受；n. 台，座"),
    ("standard", "['stændəd]", "n. 标准，水平，规格；adj. 普通的，规范的"),
    ("standpoint", "['stændpɔɪnt]", "n. 立场，观点"),
    ("stance", "[stæns]", "n.（公开表明的）观点，态度，立场；站立姿势"),
    ("start", "[stɑːt]", "v. 开始，动身；启动；n. 开端，起点"),
    ("startle", "['stɑːtl]", "v. 惊讶，惊吓，使吃惊"),
    ("starve", "[stɑːv]", "v.（使）挨饿，饿死；（for）急需，渴望"),
    ("state", "[steɪt]", "n. 状态，情况；国，州；vt. 陈述，说明"),
    ("statement", "['steɪtmənt]", "n. 声明，陈述"),
    ("statesman", "['steɪtsmən]", "n. 政治家"),
    ("statistics", "[stə'tɪstɪks]", "n. 统计数字，统计资料；统计学"),
    ("statue", "['stætʃuː]", "n. 塑像，雕塑"),
    ("status", "['steɪtəs]", "n. 地位，身份；情形，状况"),
    ("statute", "['stætʃuːt]", "n. 法令，法规，章程"),
    ("stay", "[steɪ]", "v. 停留，保持；逗留；n. 停留"),
    ("steady", "['stedi]", "adj. 稳的，牢固的；坚定的；v. 使稳固"),
    ("steer", "[stɪə(r)]", "v. 掌舵，驾驶；带领，指导"),
    ("stem", "[stem]", "n. 茎，干；词干；v. 制止；起源于"),
    ("step", "[step]", "n. 步，台阶；步骤，措施；v. 踏，走"),
    ("stern", "[stɜːn]", "adj. 严厉的，严格的；n. 船尾"),
    # ---- Unit 2：an- / cip / onym 词族 ----
    ("anonymous", "[ə'nɒnɪməs]", "adj. 匿名的，无名的；无特色的"),
    ("answer", "['ɑːnsə(r)]", "n. 答复，答案；v. 回答；负责；符合"),
    ("anticipate", "[æn'tɪsɪpeɪt]", "v. 预期，预料；先发制人；预先考虑并满足"),
    ("anxiety", "[æŋ'zaɪəti]", "n. 焦虑，担心；焦虑的原因；渴望"),
    ("anxious", "['æŋkʃəs]", "adj. 焦虑的，发愁的；（for/to）渴望的，急切的"),
    ("apart", "[ə'pɑːt]", "adv. 分离，分开；相隔；单独地"),
    ("assassinate", "[ə'sæsɪneɪt]", "vt. 暗杀，行刺；中伤"),
    ("assault", "[ə'sɔːlt]", "n./v. 攻击，袭击"),
    ("assemble", "[ə'sembl]", "v. 集合，召集；装配，组装"),
    ("assembly", "[ə'sembli]", "n. 集合，集会；装配"),
    ("assert", "[ə'sɜːt]", "v. 主张，维护；断言"),
    ("component", "[kəm'pəʊnənt]", "n. 组成部分，成分，部件；adj. 组成的"),
    ("compose", "[kəm'pəʊz]", "v. 组成；创作（音乐、文学作品）；使平静"),
    ("composition", "[ˌkɒmpə'zɪʃn]", "n. 组成；作品，作文；作曲"),
    # ---- Unit 2：com- / prehend 词族 ----
    ("comprehend", "[ˌkɒmprɪ'hend]", "vt. 理解，了解"),
    ("comprehension", "[ˌkɒmprɪ'henʃn]", "n. 理解（力），了解；阅读理解测试"),
    ("comprehensive", "[ˌkɒmprɪ'hensɪv]", "adj. 广泛的，综合的；全部的"),
    ("condemn", "[kən'dem]", "vt. 谴责；宣告有罪，判刑"),
    ("condense", "[kən'dens]", "v.（使）压缩，（使）凝结，使简洁"),
    ("condition", "[kən'dɪʃn]", "n. 状况，状态；（pl.）环境，情况"),
    ("conduct", "[kən'dʌkt]", "n. 行为，品行；v. 引导，管理，指挥；传导"),
    ("conductor", "[kən'dʌktə(r)]", "n. 领队，指挥；售票员；导体"),
    ("disable", "[dɪs'eɪbl]", "vt. 使残废，使丧失能力"),
    ("disappear", "[ˌdɪsə'pɪə(r)]", "vi. 不见，消失"),
    ("disappoint", "[ˌdɪsə'pɔɪnt]", "v. 使失望，使扫兴"),
    ("discipline", "['dɪsəplɪn]", "n. 纪律，训练；学科，专业"),
    ("disclose", "[dɪs'kləʊz]", "vt. 揭露，透露，使公开"),
    ("discover", "[dɪ'skʌvə(r)]", "vt. 发现"),
    ("discovery", "[dɪ'skʌvəri]", "n. 发现；被发现的事物"),
    ("hoist", "[hɔɪst]", "vt. 举起，升起，吊起"),
    ("hold", "[həʊld]", "v. 拿着，抓住；举行；拥有，担任；容纳；n. 掌握，控制"),
    ("holder", "['həʊldə(r)]", "n. 持有者，占有者；支持物"),
    ("household", "['haʊshəʊld]", "n. 户，家庭；adj. 家庭的"),
    # ---- Unit 2：其他高频词 ----
    ("however", "[haʊ'evə(r)]", "adv. 无论如何；然而，不过"),
    ("huddle", "['hʌdl]", "v. 蜷缩；聚集在一起；n. 挤作一团的人"),
    ("narrative", "['nærətɪv]", "n. 叙述；adj. 叙述性的"),
    ("narrow", "['nærəʊ]", "adj. 狭窄的；狭隘的"),
    ("nasty", "['nɑːsti]", "adj. 肮脏的；下流的；烦人的；厉害的"),
    ("nation", "['neɪʃn]", "n. 民族，国家"),
    ("national", "['næʃnəl]", "adj. 民族的，国家的，国立的"),
    ("nationality", "[ˌnæʃə'næləti]", "n. 国籍；民族"),
    ("native", "['neɪtɪv]", "adj. 本地的，本国的；天生的；n. 本地人"),
    ("natural", "['nætʃrəl]", "adj. 自然的，天然的；天生的"),
    ("nature", "['neɪtʃə(r)]", "n. 自然界；性质，本性"),
    ("overall", "[ˌəʊvər'ɔːl]", "adj. 全面的，总体的；adv. 总计；n.（pl.）工作服"),
    ("overcome", "[ˌəʊvə'kʌm]", "vt. 克服，战胜"),
    ("overlap", "[ˌəʊvə'læp]", "v. 重叠，部分重叠；n. 重叠部分"),
    ("portion", "['pɔːʃn]", "n.（一）部分，（食物的）一份；v. 分配"),
    ("possibility", "[ˌpɒsə'bɪləti]", "n. 可能，可能性；机会，契机"),
    ("possible", "['pɒsəbl]", "adj. 可能的，做得到的；合适的"),
    ("potential", "[pə'tenʃl]", "n. 潜力，潜能；adj. 潜在的，可能的"),
    ("pour", "[pɔː(r)]", "v. 倒，注，灌；倾泻，涌流；下倾盆大雨"),
    # ---- Unit 3：stant / sist / struct 词族 ----
    ("console", "[kən'səul]", "vt. 安慰，抚慰；n.（机器、电子设备的）控制台，仪表板"),
    ("consist", "[kən'sɪst]", "vi. 组成，构成；在于；一致，符合"),
    ("consistent", "[kən'sɪstənt]", "adj. 前后一致的；连续的，持续的；相符的"),
    ("constant", "['kɒnstənt]", "adj. 坚定的，永恒的；经常的，不断的"),
    ("constituent", "[kən'stɪtjuənt]", "adj. 构成的；n. 成分，要素；选民"),
    ("constitute", "['kɒnstɪtju:t]", "v. 组成，构成；建立，制定"),
    ("constitution", "[ˌkɒnstɪ'tju:ʃn]", "n. 构成，构造；宪法，法规"),
    ("constrain", "[kən'streɪn]", "vt. 强制，迫使；限制，约束"),
    ("construct", "[kən'strʌkt]", "v. 建造，构造；创立；n. 构想，结构体"),
    ("distinct", "[dɪ'stɪŋkt]", "adj. 有区别的，不同的；明显的，清楚的"),
    ("distinction", "[dɪ'stɪŋkʃn]", "n. 差别，区分；杰出，优秀"),
    ("distinguish", "[dɪ'stɪŋgwɪʃ]", "v. 区别，辨别；使有特色；使杰出"),
    # ---- Unit 3：fruit / fund / vid 词族 ----
    ("fruitful", "['fruːtfl]", "adj. 多产的；富有成效的"),
    ("frustrate", "[frʌ'streɪt]", "vt. 挫败，阻挠，使灰心；使无效"),
    ("fulfil/fulfill", "[fʊl'fɪl]", "vt. 履行，实现，完成；（使）满意"),
    ("function", "['fʌŋkʃn]", "n. 功能，作用；职责；函数；vi. 运行，起作用"),
    ("fund", "[fʌnd]", "n. 资金，基金；储备；v. 资助"),
    ("fundamental", "[ˌfʌndə'mentl]", "adj. 基础的，基本的；根本的；n.（pl.）基本原则"),
    ("evidence", "['evɪdəns]", "n. 证据，根据；迹象，形迹"),
    ("evident", "['evɪdənt]", "adj. 明显的，明白的"),
    ("evil", "['iːvl]", "adj. 邪恶的，罪恶的；n. 邪恶，罪行；祸害"),
    ("environment", "[ɪn'vaɪrənmənt]", "n. 环境；自然环境"),
    # ---- Unit 3：enter / mono / trans 词族 ----
    ("enterprise", "['entəpraɪz]", "n. 事业心，进取心；事业；企（事）业单位"),
    ("entertain", "[ˌentə'teɪn]", "v. 招待，款待；使……娱乐"),
    ("entertainment", "[ˌentə'teɪnmənt]", "n. 招待，款待；娱乐；文娱节目"),
    ("monopoly", "[mə'nɒpəli]", "n. 垄断，专卖；独占"),
    ("monotonous", "[mə'nɒtənəs]", "adj. 单调无聊的，毫无变化的"),
    ("mood", "[muːd]", "n. 心境，情绪，心情；氛围；语气"),
    ("transmission", "[træns'mɪʃn]", "n. 播送，发射，传送；传播"),
    ("transmit", "[trænz'mɪt]", "v. 传送，传递；播送，发射；传染"),
    ("transplant", "[træns'plɑːnt]", "v. 移植（器官等）；移种；n. 移植"),
    ("transport", "[træns'pɔːt]", "vt. 运送，运输；n. 运输；运输系统"),
    # ---- Unit 3：stock / stri / prim 词族 ----
    ("stock", "[stɒk]", "n. 原料，库存；股票；v. 储备，储存"),
    ("store", "[stɔː(r)]", "n. 商店，贮藏；vt. 贮备，保存；记忆"),
    ("storage", "['stɔːrɪdʒ]", "n. 储存，储藏，保管；库房"),
    ("stride", "[straɪd]", "v. 阔步前进；n. 大步，进展"),
    ("strike", "[straɪk]", "v. 打击，撞；突然想到；罢工；n. 罢工"),
    ("striking", "['straɪkɪŋ]", "adj. 显著的，突出的；妩媚动人的"),
    ("string", "[strɪŋ]", "n. 细绳，线，带；一串；v. 串起"),
    ("structure", "['strʌktʃə(r)]", "n. 结构体，建筑物；结构，构造；v. 系统安排"),
    ("stun", "[stʌn]", "v. 使震惊；把……打晕；n. 晕眩"),
    ("primary", "['praɪməri]", "adj. 初级的；最初的；首要的，基本的"),
    ("prime", "[praɪm]", "adj. 首要的，最好的；n. 初期，全盛时期"),
    ("primitive", "['prɪmətɪv]", "adj. 原始的，早期的；简单的，粗糙的"),
    ("principal", "['prɪnsəpl]", "adj. 最重要的；n. 校长；本金；主角"),
    ("principle", "['prɪnsəpl]", "n. 原理，原则，法则；准则"),
    # ---- Unit 3：psych / liber / ann 词族 ----
    ("psychiatry", "[saɪ'kaɪətri]", "n. 精神病学，精神病治疗法"),
    ("psychology", "[saɪ'kɒlədʒi]", "n. 心理学，心理"),
    ("liability", "[ˌlaɪə'bɪləti]", "n. 责任，义务；（pl.）债务；倾向"),
    ("liable", "['laɪəbl]", "adj. 负有责任的；有……倾向的；可能遭受……的"),
    ("liberal", "['lɪbərəl]", "adj. 自由的，慷慨的；心胸宽阔的；n. 开明的人"),
    ("liberate", "['lɪbəreɪt]", "vt. 解放，释放，使自由"),
    ("license/licence", "['laɪsns]", "n. 许可证，执照；vt. 准许，认可"),
    ("innocent", "['ɪnəsnt]", "adj. 清白的，无罪的；天真的，单纯的"),
    ("innovation", "[ˌɪnə'veɪʃn]", "n. 革新，改革，创新；新方法"),
    ("anguish", "['æŋɡwɪʃ]", "n. 极度痛苦，苦恼；v. 使痛苦"),
    ("annoy", "[ə'nɔɪ]", "vt. 使恼怒，使生气；打搅"),
    ("annual", "['ænjuəl]", "adj. 每年的，年度的；n. 年报，年鉴"),
    ("anchor", "['æŋkə(r)]", "n. 锚；精神支柱；v. 抛锚；固定"),
]
